# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-05-19T17:33:47+00:00

from __future__ import annotations

# modified by laia-gen-lib:

from pydantic import ConfigDict
from laiagenlib.Domain.LaiaBaseModel.LaiaBaseModel import LaiaBaseModel
from laiagenlib.Domain.LaiaUser.LaiaUser import LaiaUser
from laiagenlib.Domain.GeoJSON.Geometry import Type, Geometry, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class Drone(LaiaBaseModel):
    model_config = ConfigDict(json_schema_extra={'x-frontend-defaultFields': ['name', 'model', 'capabilities', 'alerts'], 'x-frontend-defaultFieldsDetail': [['name'], ['model'], ['capabilities'], ['alerts']]})
    alerts: Optional[Dict[str, Any]] = Field({}, title='Alerts', x_frontend_editable=True, x_frontend_fieldDescription="Drone's Alerts", x_frontend_fieldName="Alerts", x_frontend_placeholder="Drone's Alerts")
    capabilities: Optional[str] = Field('', title='Capabilities', x_frontend_editable=True, x_frontend_fieldDescription="These are the Capabilities of the Drone", x_frontend_fieldName="Capabilities", x_frontend_placeholder="Describe the Capabilities of the Drone")
    id: Optional[str] = Field('', title='Id', )
    model: Optional[str] = Field('', title='Model', x_frontend_editable=True, x_frontend_fieldDescription="This is the Model of the Drone", x_frontend_fieldName="Model", x_frontend_placeholder="Enter the Model of the Drone")
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the Drone Name", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of your Drone")


class FlightPlan(LaiaBaseModel):
    model_config = ConfigDict(json_schema_extra={'x-frontend-defaultFields': ['name', 'mission_details', 'route', 'departure_time', 'arrival_time', 'droneId', 'approved'], 'x-frontend-defaultFieldsDetail': [['name'], ['mission_details'], ['departure_time'], ['arrival_time'], ['droneId'], ['approved'], ['route']]})
    approved: Optional[bool] = Field(None, title='Approved', x_frontend_editable=True, x_frontend_fieldDescription="Status of the Flightplan approval", x_frontend_fieldName="Approved", x_frontend_placeholder="Toggle the Approving status", x_frontend_widget="flightplanApprovedWidget")
    arrival_time: Optional[datetime] = Field(None, title='Arrival Time', x_frontend_editable=True, x_frontend_fieldDescription="Arrival Datetime of the FlightPlan", x_frontend_fieldName="Arrival Time", x_frontend_placeholder="Select a Datetime")
    departure_time: Optional[datetime] = Field(None, title='Departure Time', x_frontend_editable=True, x_frontend_fieldDescription="Departure Datetime of the FlightPlan", x_frontend_fieldName="Departure Time", x_frontend_placeholder="Select a Datetime")
    droneId: Optional[str] = Field(None, title='Drone', x_frontend_editable=True, x_frontend_fieldDescription="This is the Drone", x_frontend_fieldName="Drone", x_frontend_placeholder="Select the Drone of this FlightPlan", x_frontend_relation="Drone")
    id: Optional[str] = Field('', title='Id', )
    mission_details: Optional[str] = Field('', title='Mission Details', x_frontend_editable=True, x_frontend_fieldDescription="Mission details of the Flight Plan", x_frontend_fieldName="Mission Details", x_frontend_placeholder="Provide the mission details")
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the name of the Flight Plan", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of the Flight Plan")
    route: Optional[LineString] = Field(None, title='Route', x_frontend_editable=True, x_frontend_fieldDescription="This is Route of the FlightPlan", x_frontend_fieldName="Route", x_frontend_placeholder="Add the coordinates for the Route", x_frontend_uspaceMap=True)
